config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'session/new', as: :new_session
  post 'session/create', as: :login
  delete 'session/destroy', as: :logout
  get 'welcome/index', as: :dashboard

  get 'mobile', to: 'welcome#mobile'
  root 'welcome#index'
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  layout "session"

  skip_before_action :login_required, except: :destroy
  before_action :required_not_login, except: [:destroy, :particles]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if !User.exists?(email: @user.email)
      flash.alert = t("alert.account_not_exist")
      render :new and return
    end

    @login_user = User.find_by(email: @user.email)

    if @login_user.password_valid?(@user.password)
      audit(current_user, "login")
      session[:user_id] = @login_user.id
      redirect_to root_path, notice: t("notice.login_success")
    else
      flash.alert = t("alert.password_invalid")
      render :new
    end
  end

  def destroy
    audit(current_user, "logout")
    session[:user_id] = nil
    redirect_to new_session_path
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.haml
.new_user_form.text-center.col-md-6.col-md-offset-3
  -#= image_tag "logo.svg", height: 80

  = simple_form_for @user, :url => login_path, class: 'login-form' do |form|
    = form.input :email, wrapper: :horizontal_input_group, label: false do
      %span.input-group-addon= fa_icon(:envelope)
      = form.input_field :email, class: "form-control"

    = form.input :password, wrapper: :horizontal_input_group, label: false do
      %span.input-group-addon= fa_icon(:key)
      = form.password_field :password, class: "form-control"

    = form.submit "登录", class: sm_btn_classes('pull-right')

  .clearfix

 

%h2
  admin@admin.com / admin